### ISSUE TITLE
스토리북 페이지 개발

### ISSUE THREAD

**Issue by metacode22** [prgrms-fe-devcourse/FEDC3_Bigtoria_Off#22]
## 작업 목록
- 스토리북 페이지 개발
  - [x] 특정 유저의 스토리 더미 데이터 생성
  - [x] 특정 유저의 스토리(post)들을 받아오는 api 작성
  - [x] StoryCard 컴포넌트를 통해 연도별로 스토리들을 렌더링
  - [x] 스토리 추가 버튼 구현
    - 스토리 추가 버튼은 어디에 둘 지
    - 로그인 한 유저만 스토리 추가 버튼이 보이게 해야 함. 유리님이 만드신 checkAuth api 머지되면 그거 사용
  - [x] 각 연도에서 월별로 나열하기(month도 출력하기)
  - [x] 디자인 변경 예정

**Comment by glassk** [comment]
- [x] 스토리북 월 flex 정렬 스타일 변경
- [x] `OOO의 스토리북` 타이틀 추가
- [x] 팔로우 버튼 추가
